name: evodiff
channels:
  # - pyg
  # - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.10.14
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - aniso8601==9.0.1
      - astroid==3.2.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - biopython==1.84
      - biotite==0.41.2
      - blinker==1.8.2
      - blosum==2.0.3
      - cachetools==5.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.2
      - commonmark==0.9.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.20.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - deprecated==1.2.14
      - dill==0.3.8
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - evodiff==1.1.0
      - git+https://github.com/microsoft/evodiff.git
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fair-esm==2.0.0
      - fasteners==0.19
      - filelock==3.15.4
      - flask==3.0.3
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - griddataformats==1.0.2
      - gunicorn==22.0.0
      - h5py==3.11.0
      - httplib2==0.22.0
      - huggingface-hub==0.24.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - isort==5.13.2
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - logomaker==0.8
      - mako==1.3.5
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mda-xdrlib==0.2.0
      - mdanalysis==2.7.0
      - mlflow==2.14.3
      - mmtf-python==1.1.3
      - mrcfile==1.5.1
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.60.0
      - numpy==1.26.4
      # - omegafold==0.0.0
      - git+https://github.com/HeliXonProtein/OmegaFold.git
      - openpyxl==3.1.5
      - opentelemetry-api==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pdb-tools==2.5.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - plantuml==0.3.0
      - plantuml-markdown==3.10.2
      - platformdirs==2.6.2
      - pluggy==1.5.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pygments==2.18.0
      - pylint==3.2.6
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pyscript==0.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyzmq==26.0.3
      - querystring-parser==1.2.4
      - regex==2024.5.15
      - requests==2.32.3
      - rich==12.6.0
      - rich-click==1.8.3
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.13.0
      # - sequence-models==1.8.0
      - git+https://github.com/microsoft/protein-sequence-models.git
      - setproctitle==1.3.3
      - smmap==5.0.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - sqlparse==0.5.1
      - stack-data==0.6.3
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.13.2
      # - torch==1.12.0+cu113
      - torch-geometric==2.5.3
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.42.4
      - typer==0.4.2
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - umap-learn==0.5.6
      - urllib3==2.2.2
      - wandb==0.17.6
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xlrd==2.0.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.19.2
